from PIL import Image
img = Image.open('/tmp/vm_screen2.ppm')
print(f'Size: {img.size}')
gray = img.convert('L')
pixels = list(gray.getdata())
min_p = min(pixels)
max_p = max(pixels)
avg_p = sum(pixels) / len(pixels)
nonblack = sum(1 for p in pixels if p > 30)
print(f'Min pixel: {min_p}, Max: {max_p}, Avg: {avg_p:.0f}')
print(f'Non-black pixels (>30): {nonblack} / {len(pixels)}')
img.save('/tmp/vm_screen.png')
print('Saved PNG')
