@echo off
echo === CAPE VM Setup Part 2 ===
echo Downloading Python from local server...
powershell -ExecutionPolicy Bypass -Command "Invoke-WebRequest -Uri 'http://10.0.2.2:8888/python_installer.exe' -OutFile 'C:\python_installer.exe' -UseBasicParsing"
echo Download complete. Installing Python...
C:\python_installer.exe /quiet InstallAllUsers=1 PrependPath=1 Include_test=0
echo Waiting for Python install (120s)...
timeout /t 120 /nobreak
echo Creating CAPE agent directory...
mkdir C:\cape_agent 2>nul
echo Downloading agent.py...
powershell -ExecutionPolicy Bypass -Command "Invoke-WebRequest -Uri 'http://10.0.2.2:8888/agent.py' -OutFile 'C:\cape_agent\agent.py' -UseBasicParsing"
echo Setting agent autorun...
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" /v CapeAgent /t REG_SZ /d "python.exe C:\cape_agent\agent.py" /f
echo === Setup Part 2 Complete ===
echo Rebooting in 10 seconds...
shutdown /r /t 10
